### ISSUE TITLE
Add programmatically text to editor

### ISSUE THREAD

**Issue by fxcosta** [DaniAkash/react-native-draftjs#1]
Hello! How do I programmatically add text to the editor? I tried in some ways but none have worked correctly. Is there anything you can use or is it still in development?

**Comment by DaniAkash** [comment]
Since the text editor is running in webview, this hasn't been implemented. But will try adding this feature in the coming weeks...

**Comment by fxcosta** [comment]
@DaniAkash I've been analyzing and realized that the magic happens with a react web page that uses draftjs as a component, right? Can you post the react code of this project so that I also try to add this functionality? I'm needing a lot but I don't know how I could add this to this lib. thanks!

**Comment by DaniAkash** [comment]
The react.js code is present inside the [`draftjs-web`](https://github.com/DaniAkash/react-native-draftjs/tree/master/draftjs-web) directory

**Comment by DaniAkash** [comment]
After trying several options I have decided this is impossible since the data in draftjs is a `EditorState` object and I can only send strings through the webview, I cannot keep the data in sync when you programmatically change the input with a new string.
