### ISSUE TITLE
Not able to run the demo app.

### ISSUE THREAD

**Issue by Krypternite** [DaniAkash/react-native-draftjs#11]
I am not able to run the demo app.
I ran
` npm install,
  cd ios, 
  pod install` and then upon building through xcode, the build succeeded but in the simulator I am getting error => Native module cannot be null
![Simulator Screen Shot - iPad mini 4 - 2019-11-08 at 10 25 09](https://user-images.githubusercontent.com/9376390/68450758-244e4e80-0212-11ea-8f98-3096239d9338.png)

**Comment by DaniAkash** [comment]
Can you try running yarn instead of npm install?
