### ISSUE TITLE
How to customize the drafts UI.

### ISSUE THREAD

**Issue by Prozhou** [DaniAkash/react-native-draftjs#12]
hi bro. I'am interested in the project. thanks for you build it. now I want to use it in my own app.
but I want build it with different UI, I want to know how did you get the `drafts-source.html`. thanks for your reply

**Comment by DaniAkash** [comment]
Hi @Prozhou thanks for your interest in the project. The source html is built using create react app and the source is inside the repo itself. Checkout [draftjs-web](https://github.com/DaniAkash/react-native-draftjs/tree/master/draftjs-web) directory.

Also, if you want to customize only the looks of the editor, you can use the styleMap or styleSheet props which can achieve style changes without any need for creating a custom fork. [Full props list](https://github.com/DaniAkash/react-native-draftjs#props)
