### ISSUE TITLE
RN 0.61.5 - custom styling not working

### ISSUE THREAD

**Issue by chasevida** [DaniAkash/react-native-draftjs#15]
Hi there, thanks heaps for this package, got it up and running super quick.

One issue I've been having is styling the actual editor. I can't seem to pass custom styles through even as a string via the `styleSheet` prop. My intention is to remove the white background and change the font and font size.

I should mention the following:

RN 0.61.5
iOS: 12.4
Device: iPad 12"
RN Draftjs Editor: 0.0.2

Any help would be greatly appreciated. Cheers :)

**Comment by DaniAkash** [comment]
Hi @chasevida the Editor is running in a web view, which means we need to use CSS for styling the editor. You can find the code for the HTML built with React at the [following file](https://github.com/DaniAkash/react-native-draftjs/blob/master/draftjs-web/src/App.js). Try specifying CSS based on the HTML

**Comment by chasevida** [comment]
Thanks @DaniAkash for pointing me in the right direction. Got it working now cheers!
