### ISSUE TITLE
What's the role of draftjs-source.html?

### ISSUE THREAD

**Issue by littlehome-eugene** [DaniAkash/react-native-draftjs#5]
I'm trying to understand how it's working at least superficially.

The following is my guess at what's happening, please correct me if I'm wrong

* create Editor component with draft.js  and have the Editor component script rendered in the html and linked via `<script>`

* define functions that's accessible globally in the html so that we can control block styles and so on

* save the html to `draftjs-source.html`

* from RN, render `draftjs-source.html` using react-native-webview

* we somehow call the functions defined in the html to acually invoke `draft.js` functions

It's a just guess, I can't tell what `draftjs-source.html` is and how it's generated

**Comment by DaniAkash** [comment]
Hi @littlehome-eugene your understanding is correct. The `draftjs-source.html` file is generated by create-react-app project which is where the editor is actually built. The code is available at [draftjs-web](https://github.com/DaniAkash/react-native-draftjs/tree/master/draftjs-web) directory
