### ISSUE TITLE
Can we add image into text editor?

### ISSUE THREAD

**Issue by nlshuynguyen** [DaniAkash/react-native-draftjs#8]
I want to add image in text editor. Is it possible to do that?

**Comment by DaniAkash** [comment]
Unfortunately, I haven't planned on adding images into the text editor. Draft.js itself doesn't support adding images and if you wanna add images, you need to install additional plugins such as https://www.draft-js-plugins.com/plugin/image which will increase the complexity of this react native wrapper. 

React native itself needs some libraries installed to pick images, so I have no plans for adding images any time soon...
